### ISSUE TITLE
Can't require the npm module

### ISSUE THREAD

**Issue by msegundo** [cjohansen/js-atom#1]
Hi, thanks for the module.

If the name of the npm module is js-atom, to be able to require this npm module the name of the main file should be js-atom.js and now is called atom.js.

If you prefer you can add a main property with the file name ./atom.js to the package.json.

**Comment by msegundo** [comment]
Sorry, index.js is by default.

**Comment by cjohansen** [comment]
Thanks, fixed and pushed as 0.4.0
